import { experiences, projects, skillGroups } from '../data';
import { FaReact,FaNodeJs,FaPython,FaJava,FaDocker,FaGitAlt,FaAws } from 'react-icons/fa';
import { SiNextdotjs,SiTypescript,SiJavascript,SiPostgresql,SiMongodb,SiRedis,SiTailwindcss,SiPytorch,SiTensorflow,SiPrisma,SiVercel,SiCplusplus,SiC,SiLinux } from 'react-icons/si';
import '../styles/PortfolioPanels.css';

const skillIcons={React:<FaReact/>, 'Node.js':<FaNodeJs/>,Python:<FaPython/>,Java:<FaJava/>,Docker:<FaDocker/>,Git:<FaGitAlt/>, 'AWS S3':<FaAws/>,'Next.js':<SiNextdotjs/>,TypeScript:<SiTypescript/>,JavaScript:<SiJavascript/>,PostgreSQL:<SiPostgresql/>,MongoDB:<SiMongodb/>,Redis:<SiRedis/>,TailwindCSS:<SiTailwindcss/>,PyTorch:<SiPytorch/>,TensorFlow:<SiTensorflow/>,Prisma:<SiPrisma/>,Vercel:<SiVercel/>,'C++':<SiCplusplus/>,C:<SiC/>,Linux:<SiLinux/>};

export function AboutPanel(){return <div className="about-panel"><div className="about-hero"><img src="/assets/UserProfileImg.jpeg"/><div><p className="eyebrow">C:\Users\Aakarsh\profile.exe</p><h1>Aakarsh Agarwal</h1><h2>Software Engineer · Full Stack · Backend · AI · Low-Level Systems</h2><p>I build products that move between browser interfaces, backend systems, operations automation, intelligent agents and bare-metal computing. Friends call me Chandler, and I genuinely prefer that nickname.</p><div className="xp-badges"><span>BIT Mesra AIML</span><span>CGPA 8.59</span><span>New Delhi</span><span>Open to SDE Internships</span></div></div></div><div className="about-grid"><section><h3>Current system status</h3><p>Third-year B.Tech student focused on software engineering roles, production-grade web/backend work and ambitious systems projects.</p></section><section><h3>What I ship</h3><p>Next.js platforms, Node APIs, PostgreSQL systems, spreadsheet automation, browser agents, ML prototypes and an x86 operating system.</p></section><section><h3>Developer philosophy</h3><p>Understand the workflow, remove the repetitive parts, make the interface delightful, and keep the architecture maintainable.</p></section><section><h3>Beyond code</h3><p>Technical Lead at E-Cell, BIT Mesra, supporting event systems used across hundreds of registrations.</p></section></div></div>}

export function ExperiencePanel(){return <div className="experience-panel">{experiences.map((e,i)=><article key={e.company} className="experience-card"><div className="experience-icon">{e.icon}</div><div className="experience-copy"><header><div><h3>{e.role}</h3><h4>{e.company}</h4></div><div className="experience-meta">{e.date}<br/><span>{e.location}</span></div></header><ul>{e.bullets.map(b=><li key={b}>{b}</li>)}</ul><div className="stack-row">{e.tools.map(t=><span key={t}>{t}</span>)}</div></div></article>)}</div>}

export function ProjectsPanel({openBrowser}){return <div className="projects-panel">{projects.map(p=><article className="project-card" key={p.name}><img src={p.image} alt=""/><div className="project-body"><div className="project-title"><span className="project-emoji">{p.icon}</span><div><h3>{p.name}</h3><p>{p.kind} · {p.year}</p></div></div><p className="project-desc">{p.description}</p><div className="stack-row">{p.stack.map(s=><span key={s}>{s}</span>)}</div><div className="project-actions">{p.live&&<button onClick={()=>openBrowser(p.live,p.name)}>🌐 Live Demo</button>}{p.learn&&<button onClick={()=>openBrowser(p.learn,`${p.name} - Technical Guide`)}>📖 How It Works</button>}{p.github&&<button onClick={()=>openBrowser(p.github,`${p.name} - GitHub`)}>📁 Source</button>}</div></div></article>)}</div>}

export function SkillsPanel(){return <div className="skills-panel">{skillGroups.map(([group,skills])=><section key={group}><h3>{group}</h3><div className="skills-grid">{skills.map(s=><div className="skill-tile" key={s}><span>{skillIcons[s]||'⚙️'}</span><b>{s}</b></div>)}</div></section>)}</div>}

export function PhotosPanel(){return <div className="photos-panel"><div className="photo-placeholder"><span>📷</span><h2>My Pictures</h2><p>This XP folder is ready for your personal gallery. Drop images into <code>public/photos</code> and add them here.</p></div></div>}
